#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely and handles SIGTERM

function handle_sigterm {
    echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
